composer.json

We do not know if we support PHP8 yet..

Better syntax on PHP requirement

---

.travis.yml
composer.json

Blocked by https://github.com/backup-manager/backup-manager/issues/134

Enable Symfony 4 support

---

DependencyInjection/BMBackupManagerExtension.php
Resources/config/services.yml
Tests/Functional/BundleInitializationTest.php
Tests/Functional/config/rackspace.yml
composer.json

This is a BC break and next version after this is merged should be 2.0

Validate we got the proper dependencies.

---

Changelog.md

Added changelog for upcoming release

Added changelog

---

Command/BackupCommand.php
Command/RestoreCommand.php
DependencyInjection/BMBackupManagerExtension.php
DependencyInjection/Configuration.php
README.md
Resources/config/services.yml
composer.json

We want an easy way to backup and restore databases.

Adding console commands

---

DependencyInjection/Configuration.php
README.md
Tests/Unit/DependencyInjection/BMBackupManagerExtensionTest.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

Adding support for ignoreTables

---

DependencyInjection/Configuration.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

Adding support for "ssl" and "singleTransaction"

---

DependencyInjection/BMBackupManagerExtension.php
DependencyInjection/Configuration.php
Tests/Functional/BundleInitializationTest.php
Tests/Functional/config/public_services.yml
composer.json

Make sure we can use the bundle with no config.

---

Resources/config/services.yml

Commands should not be marked as public: false

---

DependencyInjection/BMBackupManagerExtension.php
DependencyInjection/Configuration.php
README.md
Tests/Unit/DependencyInjection/BMBackupManagerExtensionTest.php
composer.json

Allow for DSN values

---

README.md

Updated readme to show the environment variable.

---

.travis.yml
Changelog.md
DependencyInjection/BMBackupManagerExtension.php
DependencyInjection/Configuration.php
Tests/Functional/BundleInitializationTest.php
Tests/Unit/DependencyInjection/BMBackupManagerExtensionTest.php
Tests/Unit/DependencyInjection/ConfigurationTest.php

Allow for DropboxV2

---

README.md

Update readme to target sf 4

---

DependencyInjection/Configuration.php

See: https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

Fix root node deprecation in symfony/config > 4.1

---

README.md

It makes more sense to me like that.  Am I wrong ?

Doc typo ?

---

composer.json

https://github.com/backup-manager/symfony/issues/62

Support Symfony 5

---

Command/BackupCommand.php

When i call `backup-manager:backup` in another command. destinations arg  confuses me.

update backup command help info.

---

.travis.yml
Changelog.md
Command/BackupCommand.php
README.md
Tests/Functional/BundleInitializationTest.php
Tests/Unit/DependencyInjection/BMBackupManagerExtensionTest.php
composer.json
phpunit.xml.dist

Blocked by https://github.com/SymfonyTest/symfony-bundle-test/pull/26

Drop old versions and bump php to 7.2

---

Changelog.md

The updated Changelog for changes done in #67

Added changes

---

DependencyInjection/BMBackupManagerExtension.php

Fixed typo in BMBackupManagerExtension.php

---

DependencyInjection/Configuration.php

See https://github.com/backup-manager/backup-manager/pull/153

Allow 'endpoint' option in AwsS3 storage configuration

---

Factory/ConfigFactory.php
composer.json

This PR should not be merged before we can drop the beta flag.

Add support for DSN v2

---

Factory/ConfigFactory.php
Tests/Unit/Factory/ConfigFactoryTest.php

Added fix for database as path in DSN

---

README.md
Resources/config/services.yml

Updated readme and added alias for Manager
